# Stage a TMAC CMake package prefix for OHOS llama.cpp (no TVM).
# Output: ohos/staging/t-mac/{lib,include,lib/cmake/t-mac}
$ErrorActionPreference = "Stop"
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$KernelDir = Join-Path $RepoRoot "deploy\tuned\aarch64-hf-bitnet-3b"
$Stage = Join-Path $RepoRoot "ohos\staging\t-mac"
$Lib = Join-Path $Stage "lib"
$Inc = Join-Path $Stage "include\t-mac"
$Cmake = Join-Path $Stage "lib\cmake\t-mac"

New-Item -ItemType Directory -Force -Path $Lib,$Inc,$Cmake | Out-Null
Copy-Item (Join-Path $KernelDir "kernels.cc") $Lib -Force
Copy-Item (Join-Path $KernelDir "kernels.h") $Lib -Force
Copy-Item (Join-Path $KernelDir "kernels.h") (Join-Path $Inc "kernels.h") -Force
Copy-Item (Join-Path $KernelDir "kcfg.ini") $Lib -Force
Copy-Item (Join-Path $RepoRoot "include\t-mac\*") $Inc -Force

# Shim wins for dmlc when consumers add ohos/shim — also drop a copy under include for package users
$ShimDmlc = Join-Path $Stage "include\dmlc"
New-Item -ItemType Directory -Force -Path $ShimDmlc | Out-Null
Copy-Item (Join-Path $RepoRoot "ohos\shim\dmlc\logging.h") (Join-Path $ShimDmlc "logging.h") -Force

$KcfgCmake = ($Lib + "/kcfg.ini") -replace '\\','/'
$KernelsCmake = ($Lib + "/kernels.cc") -replace '\\','/'
$IncCmake = ((Join-Path $Stage "include") -replace '\\','/')

@"
# Generated by ohos/scripts/stage_tmac_prefix.ps1 — OHOS no-TVM package
get_filename_component(_TMAC_PREFIX "`${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
set(TMAC_LIB_DIR "`${_TMAC_PREFIX}/lib")
set(TMAC_INCLUDE_DIRS "`${_TMAC_PREFIX}/include")
set(TMAC_KERNELS_SOURCE "`${TMAC_LIB_DIR}/kernels.cc")
set(tuned_kcfg "`${TMAC_LIB_DIR}/kcfg.ini")
set(TMAC_COMPILE_DEFS "TMAC_KCFG_FILE=`${tuned_kcfg}")
set(TMAC_FOUND TRUE)

if(NOT TARGET t_mac_no_tvm)
  add_library(t_mac_no_tvm INTERFACE)
  set_target_properties(t_mac_no_tvm PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "`${TMAC_INCLUDE_DIRS}"
    INTERFACE_COMPILE_DEFINITIONS "`${TMAC_COMPILE_DEFS}"
    INTERFACE_COMPILE_FEATURES cxx_std_17
    POSITION_INDEPENDENT_CODE ON
  )
endif()
"@ | Set-Content -Encoding ascii (Join-Path $Cmake "TMACConfig.cmake")

Write-Host "Staged: $Stage"
Write-Host "Set TMAC_DIR=$Cmake when configuring llama.cpp"
Write-Host "Or CMAKE_PREFIX_PATH=$Stage"
